In [14]:
import pandas as pd
import camelot

def clean(df):
    # Skipping the first few header rows which don't contain actual data
    for j in range(0, df.shape[0]):
        try:
            int(df.iloc[j, 0])
            df = df.iloc[j:].reset_index(drop=True)
            break
        except:
            continue
    return df

def append_table(tables):
    df = pd.DataFrame()
    for i in range(tables.n):
        df = pd.concat([df, clean(tables[i].df)], ignore_index=True)
    return df

def process_pdf(file_path, year):
    try:
        tables = camelot.read_pdf(file_path, pages='all', flavor='stream')
        df = append_table(tables)
        
        # Define the expected columns
        expected_columns = [
            'Sr No', 'Subsidiary', 'Country', 'Reporting currency', 'Exchange Rate', 
            'Share capital (incl. advances towards capital where applicable)', 
            'Reserves and Surplus', 'Total Assets', 'Total Liabilities', 
            'Turnover', 'Profit/(Loss) Before Tax', 'Tax Expense/(Credit)', 
            'Profit/(Loss) after tax', 'Profit/(Loss) for the period/year *', 
            'Proposed dividend and tax thereon', 'Investments (except in case of investment in the subsidiaries)', 
            '% of shareholding'
        ]
        
        # Adjust the columns of the dataframe
        if df.shape[1] >= len(expected_columns):
            df = df.iloc[:, :len(expected_columns)]  # Take only the required number of columns
            df.columns = expected_columns
        else:
            df.columns = expected_columns[:df.shape[1]]
        
        df['Year'] = year
        return df
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return pd.DataFrame()

# List of PDF files and the corresponding years
pdf_files = [
    ('Subsidiaries-2014-15.pdf', '2014-15'),
    ('Subsidiaries-2015-16.pdf', '2015-16'),
    ('Subsidiaries-2016-17.pdf', '2016-17'),
    ('Subsidiaries-2017-18.pdf', '2017-18'),
    ('Subsidiaries-2018-19.pdf', '2018-19'),
    ('Subsidiaries-2019-20.pdf', '2019-20'),
    ('Subsidiaries-2020-21.pdf', '2020-21'),
    ('Subsidiaries-2022-23.pdf', '2022-23'),
    ('Subsidiaries-2023-24.pdf', '2023-24')
]

# Initialize an empty DataFrame to store the consolidated data
consolidated_df = pd.DataFrame()

# Process each PDF file and append the data to the consolidated DataFrame
for file, year in pdf_files:
    pdf_df = process_pdf(file, year)
    consolidated_df = pd.concat([consolidated_df, pdf_df], ignore_index=True)

# Convert numerical columns to the appropriate data type
numerical_columns = [
    'Exchange Rate', 'Share capital (incl. advances towards capital where applicable)', 
    'Reserves and Surplus', 'Total Assets', 'Total Liabilities', 
    'Turnover', 'Profit/(Loss) Before Tax', 'Tax Expense/(Credit)', 
    'Profit/(Loss) after tax', 'Profit/(Loss) for the period/year *', 
    'Proposed dividend and tax thereon', 'Investments (except in case of investment in the subsidiaries)', 
    '% of shareholding'
]

for column in numerical_columns:
    consolidated_df[column] = consolidated_df[column].replace(',', '', regex=True)
    consolidated_df[column] = pd.to_numeric(consolidated_df[column], errors='coerce')

# Drop any remaining rows with NaN values
consolidated_df.dropna(how='all', inplace=True)

# Display the consolidated data
consolidated_df

# Save the consolidated DataFrame to an Excel file
consolidated_df.to_excel('Consolidated_Subsidiary_Data_Cleaned.xlsx', index=False)

                                  Sr No  \
0                                     1
1                                     2
2                                     3
3                                     4
4                                     5
...                                 ...
1860
1861
1862  (subsidiary w.e.f March 30, 2004)
1863                   PT  Tata  Motors
1864                 December 29, 2011)

                                        Subsidiary      Country  \
0                  TAL Manufacturing Solutions Ltd        India
1                               TML Drivelines Ltd        India
2                      Concorde Motors (India) Ltd        India
3                             Sheba Properties Ltd        India
4           Tata Daewoo Commercial Vehicle Co. Ltd  South Korea
...                                            ...          ...
1860  Consolidated (subsidiary w.e.f June 2, 2008)
1861   Tata  Daewoo  Commercial  Vehicle  Co.  Ltd
1862
1863                 Indonesia  (subsidiary  w.e.f
1864

       Reporting currency  Exchange Rate  \
0                     INR           1.00
1                     INR           1.00
2                     INR           1.00
3                     INR           1.00
4                     KRW           0.06
...                   ...            ...
1860  105.03 \n 15,764.43       60684.14
1861                                 NaN
1862        0.06 \n 93.38        2096.34
1863                                 NaN
1864       0.01 \n 406.88            NaN

      Share capital (incl. advances towards capital where applicable)  \
0                                                100.00
1                                                 77.00
2                                                 43.04
3                                                 75.00
4                                                 57.35
...                                                 ...
1860                                          256999.11
1861                                                NaN
1862                                            3985.98
1863                                                NaN
1864                                              90.12

      Reserves and Surplus  Total Assets  Total Liabilities  Turnover  \
0                      NaN        235.96             167.01    143.25
1                   709.26        991.23             204.97    527.06
2                      NaN        354.82             365.34    777.54
3                   115.56        193.74               3.18      1.50
4                  1801.77       3596.94            1737.82   5737.96
...                    ...           ...                ...       ...
1860             180550.54     304523.47           22738.17       NaN
1861                   NaN           NaN                NaN       NaN
1862               1796.26       6192.66             216.66     43.65
1863                   NaN           NaN                NaN       NaN
1864                 91.51         63.75                NaN      0.51

      Profit/(Loss) Before Tax  Tax Expense/(Credit)  Profit/(Loss) after tax  \
0                          NaN                   NaN                      NaN
1                        62.47                 15.62                    46.85
2                          NaN                   NaN                      NaN
3                        19.10                  2.93                    16.17
4                       460.17                100.31                   359.86
...                        ...                   ...                      ...
1860                  27075.75              27075.75                      NaN
1861                       NaN                   NaN                      NaN
1862                    173.01                173.01                    46.69
1863                       NaN                   NaN                      NaN
1864                       NaN                   NaN                      NaN

      Profit/(Loss) for the period/year *  Proposed dividend and tax thereon  \
0                                     NaN                                NaN
1                                   46.85                              23.17
2                                     NaN                                NaN
3                                   16.17                                NaN
4                                  359.86                                NaN
...                                   ...                                ...
1860                              1627.91                             100.00
1861                                  NaN                                NaN
1862                                  NaN                             100.00
1863                                  NaN                                NaN
1864                                  NaN                             100.00

      Investments (except in case of investment in the subsidiaries)  \
0                                                   NaN
1                                                 25.00
2                                                   NaN
3                                                165.48
4                                                  3.95
...                                                 ...
1860                                                NaN
1861                                                NaN
1862                                                NaN
1863                                                NaN
1864                                                NaN

      % of shareholding     Year
0                 100.0  2014-15
1                 100.0  2014-15
2                 100.0  2014-15
3                 100.0  2014-15
4                 100.0  2014-15
...                 ...      ...
1860                NaN  2023-24
1861                NaN  2023-24
1862                NaN  2023-24
1863                NaN  2023-24
1864                NaN  2023-24

[1865 rows x 18 columns]